# Generated by Django 3.2 on 2022-02-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_review', '0002_boxreview_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxreview',
            name='review_rating',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0),
        ),
    ]
