# Generated by Django 3.2 on 2022-02-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220203_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='product',
            field=models.ManyToManyField(related_name='product', to='products.Product'),
        ),
    ]
