# Generated by Django 3.2 on 2022-02-09 19:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220209_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='product',
            field=models.ManyToManyField(related_name='product', to='products.Product'),
        ),
        migrations.RemoveField(
            model_name='product_on_box',
            name='product',
        ),
        migrations.AddField(
            model_name='product_on_box',
            name='product',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
