# Generated by Django 3.2 on 2022-02-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220209_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='product',
        ),
    ]
