# Generated by Django 3.2 on 2022-01-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
