# Generated by Django 3.2 on 2022-01-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='profile_user',
            new_name='user',
        ),
    ]
