# Generated by Django 3.2 on 2022-02-01 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_address1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_address2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_county',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_eircode',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('eircode', models.CharField(max_length=7)),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], default='S', max_length=1)),
                ('default', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'adresses',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address1', to='user_profile.address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address2', to='user_profile.address'),
        ),
    ]
