# Generated by Django 3.2 on 2022-02-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbox',
            name='selected_products',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
