# Generated by Django 3.2 on 2022-01-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_countries_billingaddress_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='complete',
        ),
    ]
