# Generated by Django 3.2 on 2022-01-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220120_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='ordered',
        ),
    ]
