# Generated by Django 3.2 on 2022-01-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20220125_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'adresses'},
        ),
        migrations.AlterField(
            model_name='address',
            name='eircode',
            field=models.CharField(max_length=7),
        ),
    ]
