# Generated by Django 3.2 on 2022-01-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20220125_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transactional_id',
            field=models.UUIDField(default=1),
        ),
    ]
