# Generated by Django 3.2 on 2022-01-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_transactional_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transactional_id',
            field=models.UUIDField(null=True),
        ),
    ]
