# Generated by Django 3.2 on 2022-01-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20220125_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uuid',
        ),
        migrations.AddField(
            model_name='order',
            name='transactional_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
