# Generated by Django 3.2 on 2022-01-25 21:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20220125_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transactional_id',
        ),
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
