# Generated by Django 3.2 on 2022-01-31 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile'),
        ('order', '0019_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbox',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_boxes', to='user_profile.userprofile'),
        ),
    ]
