# Generated by Django 3.2 on 2022-02-02 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0021_auto_20220201_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbox',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='orderbox',
            name='customer',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
