# Generated by Django 3.2 on 2022-02-02 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_orderbox_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbox',
            name='customer',
        ),
    ]
