# Generated by Django 3.2 on 2022-02-03 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(max_length=200)),
                ('box_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('category', models.CharField(max_length=50, unique=True)),
                ('box_description', models.TextField()),
                ('box_image', models.ImageField(null=True, upload_to='')),
                ('box_note1', models.TextField(null=True)),
                ('box_note2', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('product_description', models.TextField()),
                ('product_note1', models.TextField(null=True)),
                ('product_note2', models.TextField(null=True)),
                ('product_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product_On_Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_selectable', models.BooleanField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.box')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
