# Generated by Django 3.2 on 2022-02-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='box',
            name='box_note1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='box_note2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
