# Generated by Django 3.2 on 2022-02-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220213_1025'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product_on_box',
            constraint=models.UniqueConstraint(fields=('product', 'box'), name='productsunique'),
        ),
    ]
