# Generated by Django 3.2 on 2022-02-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_on_box_productsunique'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_On_Box',
            new_name='ProductOnBox',
        ),
    ]
