# Generated by Django 3.2 on 2022-01-11 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220110_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(max_length=200)),
                ('box_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('category', models.CharField(max_length=50, unique=True)),
                ('box_description', models.TextField()),
                ('box_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='boxname',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_option1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_option2',
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='Product_On_Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_selectable', models.BooleanField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.box')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
