# Generated by Django 3.2 on 2022-01-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220111_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_note1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_note2',
            field=models.TextField(null=True),
        ),
    ]
