# Generated by Django 3.2 on 2022-01-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220129_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='box_note1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='box_note2',
            field=models.TextField(null=True),
        ),
    ]
